language: node_js
node_js:
  - "8.0"
script: 
  - echo "Deploying..."
deploy:
  provider: firebase
  token:
    secure: U40OYd3T/kQp+62zxiUPWK/tUnTxhb4Z6pLVNdXjnnAPCtiHgLJD3fzONokDhKto0ef5jjW9sMr3ePyRHv5EcGKA2wqKTD3OHaEcipwHNgquUIU9MK226Z4oUjG48CQlZIVoKeIK9bRFro0Y2WiqV9hdJO1oGm+thHrB8XCr1fiH+9BJS+iDNvM7nrpVqDnA0rCEuFX1PB5p9JMXX65sofdRiNYqvBegboy/5vrQ7O/fy9V+DkCQGsu0m8FxX+cD9BdmscmbN3WHXwfYi3i0eMdaMHsSCx5rkYetQtg9HCMGLygzuiue1wxI7fDf+AmlSyd+l41Iue7qHM2lAuoUGgA8tJmroUoIwSwB7WYNePExD76P2gqiDiGa6Wqu/ZkSCYu2MUERQY6UqwTFkrfdH9E73LUk0yUfKUpwoqdwPEXZKvdbFBgGex2GXVxu2oHFG07hXlSv9g3x8uK2QVMyhh1MPMdD7YHLwcejohpB5nNxd6iOOYl9W/2bNV8UEVPN6gAi97V2VfLhaaIZzzq0k7J8mhItGFsUpluo/gnc5fHnPeF8t73iK4vg9AVKVDqCajcU2GQA5wRY92DZITd9/LWnS+18Zqbx/nE+9RCuMhAlCBGGf8EPoDm/4olRv3Bz7EwmJROtjuYgpxXV2CuUhMiNSUBOjeehqHhJN86FwYs=
