language: node_js
node_js:
  - "8.0"
script: 
  - echo "Deploying..."
after_success:
  deploy:
    provider: firebase
    token:
      secure: "QKVK6CKnYMljnffFHSRVwJ0D72M7hTMWNrj5PXIaZfHiW3FGvtCgUIpxPrpVZDdoFR3XNF5fewRSouxXlC4K9BF+r5JljJwhcg3cHKZwt8TNxhfX91n+EgllM6YHM84pDaGrTsHsTuIaSX6f+qdgkoZxPS3xNnsN4DwHsdXmaoh1CLqAyvPi5gMz/F2W9QnmsOxYkfrEoU5i3DfVCn3SObaM32hexVKjU58WM/uksXriT+XjCqN/DXPeLtCQxGfoTZ5uAaPbomRKTmlWP/wrz3kjZc/vRujGecNfSW/2dRXIN2G63YXzIsMWP/pUdo59LBtoONN3iOJAjGWTBrvd1MYAiyK9hLqZWRiPxSRyXouLrwIL3VCQ/vq/Bw1Ojz9dyDPKSIZ2Xqllv8JBSmRYlc+O2dkakl54jvPapQciJjqdD3PjqzwXvUxNUlQJvsSinNh9Fl3psNhRIEyoH4hGTbDLfc+55hweOGhvHoZGxAixvbKFUc2/ftmNO0DBGSlZknVnJSWd9UUAl8fbwDO+//X1Pdwchg5NbsHT+qnXMOU08jcKfse57KPFL6ZmoLzqt4jOw2amu7dgGDnfumdDFExqXeQZ9yjFcYS2wyvR31GGRADUYkm7xieyUOSv1Su4kDJeDyPKG/sKrr9jvf9HgS3eot1MhlhZvjX4s73eJ0Y="
