name: Deploy to Firebase
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install firebase-tools
        run: |
          cd functions
          npm install firebase-tools
      - name: Setup firebase
        run: npm run firebase ailas default
      - name: Deploy
        run: npm run firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
