name: CI

on:
  push:
    branches: 
    - Functions

jobs:
  firebase-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@Functions
    - uses: actions/setup-node@Functions
      with:
        node-version: '8.x'  
    - uses: w9jds/firebase-action@master
      with:
        args: deploy --only functions
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
